### ISSUE TITLE
Tests do not consistently pass

### ISSUE THREAD

**Issue by matthewelwell** [Flagsmith/flagsmith-elixir-client#20]
It seems that the tests are not environment agnostic. Running `mix test` on my machine multiple times will, seemingly, provide a random amount of test failures between 1 & 3. 

Example failed tests from 3 consecutive `mix test` runs: 

### Run 1

```
  1) test api call errors initializing with api error (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:517
     ** (Mox.VerificationError) error while verifying mocks for #PID<0.569.0>:
     
       * expected Tesla.Adapter.Mock.call/2 to be invoked once but it was invoked 0 times
```

```
  2) test api call errors refresh with errors retries in next cycle (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:541
     Expected truthy, got false
     code: assert Enum.reduce_while(1..100, false, fn _, acc ->
             receive do
               {:trace, ^pid, :spawn, spawned_pid,
                {Flagsmith.Client.Poller, :get_environment, [^pid, ^config]}} ->
                 allow(Tesla.Adapter.Mock, self(), spawned_pid)
           
                 case acc do
                   true -> {:halt, true}
                   false -> {:cont, true}
                 end
           
               _others ->
                 {:cont, false}
             after
               200 -> {:halt, false}
             end
           end)
     arguments:

         # 1
         1..100

         # 2
         false

         # 3
         #Function<5.99259602/2 in Flagsmith.Client.Poller.Test."test api call errors refresh with errors retries in next cycle"/1>

     stacktrace:
       test/flagsmith_poller_test.exs:599: (test)
```

```
  3) test poller requests when a call to a poller that was started with a given configuration is given another configuration replace the __configuration__ in the returned environment (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:463
     ** (EXIT from #PID<0.618.0>) an exception was raised:
         ** (Mox.UnexpectedCallError) no expectation defined for Tesla.Adapter.Mock.call/2 in process #PID<0.626.0> (or in its callers [#PID<0.625.0>]) with args [%Tesla.Env{method: :get, url: "https://edge.api.flagsmith.com/api/v1/environment-document/", query: [], headers: [{"X-Environment-Key", "test_key"}], body: nil, status: nil, opts: [], __module__: Tesla, __client__: %Tesla.Client{fun: nil, pre: [{Tesla.Middleware.BaseUrl, :call, ["https://edge.api.flagsmith.com/api/v1/"]}, {Tesla.Middleware.Headers, :call, [[{"X-Environment-Key", "test_key"}]]}, {Tesla.Middleware.JSON, :call, [[]]}, {Tesla.Middleware.Retry, :call, [[max_retries: 0]]}, {Tesla.Middleware.Headers, :call, [[]]}, {Tesla.Middleware.FollowRedirects, :call, [[max_redirects: 5]]}, {Tesla.Middleware.Timeout, :call, [[timeout: 5000]]}], post: [], adapter: nil}}, []]
             (mox 1.0.1) lib/mox.ex:741: Mox.__dispatch__/4
             (tesla 1.4.4) lib/tesla/middleware/timeout.ex:45: anonymous fn/1 in Tesla.Middleware.Timeout.safe_async/1
             (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
             (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
             (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

### Run 2

```
  1) test api call errors refresh with errors retries in next cycle (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:541
     Expected truthy, got false
     code: assert Enum.reduce_while(1..100, false, fn _, acc ->
             receive do
               {:trace, ^pid, :spawn, spawned_pid,
                {Flagsmith.Client.Poller, :get_environment, [^pid, ^config]}} ->
                 allow(Tesla.Adapter.Mock, self(), spawned_pid)
           
                 case acc do
                   true -> {:halt, true}
                   false -> {:cont, true}
                 end
           
               _others ->
                 {:cont, false}
             after
               200 -> {:halt, false}
             end
           end)
     arguments:

         # 1
         1..100

         # 2
         false

         # 3
         #Function<5.99259602/2 in Flagsmith.Client.Poller.Test."test api call errors refresh with errors retries in next cycle"/1>

     stacktrace:
       test/flagsmith_poller_test.exs:599: (test)
```

```
  2) test api call errors initializing with api error (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:517
     ** (Mox.VerificationError) error while verifying mocks for #PID<0.509.0>:
     
       * expected Tesla.Adapter.Mock.call/2 to be invoked once but it was invoked 0 times
     stacktrace:
       (mox 1.0.1) lib/mox.ex:713: Mox.verify_mock_or_all!/3
       (ex_unit 1.14.0) lib/ex_unit/on_exit_handler.ex:143: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit 1.14.0) lib/ex_unit/on_exit_handler.ex:129: ExUnit.OnExitHandler.on_exit_runner_loop/0
```

```
  3) test poller init and refresh the refresh works accordingly (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:115
     ** (EXIT from #PID<0.521.0>) an exception was raised:
         ** (Mox.UnexpectedCallError) no expectation defined for Tesla.Adapter.Mock.call/2 in process #PID<0.529.0> (or in its callers [#PID<0.528.0>]) with args [%Tesla.Env{method: :get, url: "https://edge.api.flagsmith.com/api/v1/environment-document/", query: [], headers: [{"X-Environment-Key", "test_key"}], body: nil, status: nil, opts: [], __module__: Tesla, __client__: %Tesla.Client{fun: nil, pre: [{Tesla.Middleware.BaseUrl, :call, ["https://edge.api.flagsmith.com/api/v1/"]}, {Tesla.Middleware.Headers, :call, [[{"X-Environment-Key", "test_key"}]]}, {Tesla.Middleware.JSON, :call, [[]]}, {Tesla.Middleware.Retry, :call, [[max_retries: 0]]}, {Tesla.Middleware.Headers, :call, [[]]}, {Tesla.Middleware.FollowRedirects, :call, [[max_redirects: 5]]}, {Tesla.Middleware.Timeout, :call, [[timeout: 5000]]}], post: [], adapter: nil}}, []]
             (mox 1.0.1) lib/mox.ex:741: Mox.__dispatch__/4
             (tesla 1.4.4) lib/tesla/middleware/timeout.ex:45: anonymous fn/1 in Tesla.Middleware.Timeout.safe_async/1
             (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
             (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
             (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

### Run 3

```
  1) test api call errors refresh with errors retries in next cycle (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:541
     Expected truthy, got false
     code: assert Enum.reduce_while(1..100, false, fn _, acc ->
             receive do
               {:trace, ^pid, :spawn, spawned_pid,
                {Flagsmith.Client.Poller, :get_environment, [^pid, ^config]}} ->
                 allow(Tesla.Adapter.Mock, self(), spawned_pid)
           
                 case acc do
                   true -> {:halt, true}
                   false -> {:cont, true}
                 end
           
               _others ->
                 {:cont, false}
             after
               200 -> {:halt, false}
             end
           end)
     arguments:

         # 1
         1..100

         # 2
         false

         # 3
         #Function<5.99259602/2 in Flagsmith.Client.Poller.Test."test api call errors refresh with errors retries in next cycle"/1>

     stacktrace:
       test/flagsmith_poller_test.exs:599: (test)
```

```
  2) test poller init and refresh the refresh works accordingly (Flagsmith.Client.Poller.Test)
     test/flagsmith_poller_test.exs:115
     ** (EXIT from #PID<0.501.0>) an exception was raised:
         ** (Mox.UnexpectedCallError) no expectation defined for Tesla.Adapter.Mock.call/2 in process #PID<0.509.0> (or in its callers [#PID<0.508.0>]) with args [%Tesla.Env{method: :get, url: "https://edge.api.flagsmith.com/api/v1/environment-document/", query: [], headers: [{"X-Environment-Key", "test_key"}], body: nil, status: nil, opts: [], __module__: Tesla, __client__: %Tesla.Client{fun: nil, pre: [{Tesla.Middleware.BaseUrl, :call, ["https://edge.api.flagsmith.com/api/v1/"]}, {Tesla.Middleware.Headers, :call, [[{"X-Environment-Key", "test_key"}]]}, {Tesla.Middleware.JSON, :call, [[]]}, {Tesla.Middleware.Retry, :call, [[max_retries: 0]]}, {Tesla.Middleware.Headers, :call, [[]]}, {Tesla.Middleware.FollowRedirects, :call, [[max_redirects: 5]]}, {Tesla.Middleware.Timeout, :call, [[timeout: 5000]]}], post: [], adapter: nil}}, []]
             (mox 1.0.1) lib/mox.ex:741: Mox.__dispatch__/4
             (tesla 1.4.4) lib/tesla/middleware/timeout.ex:45: anonymous fn/1 in Tesla.Middleware.Timeout.safe_async/1
             (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
             (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
             (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by khvn26** [comment]
I believe this can be closed.
